apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: edge 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edge 
    spec:
      containers:
        - name: edge 
          image: acubedcr.azurecr.io/edge
          ports:
          - containerPort: 80