apiVersion: v1
kind: Service
metadata:
    name: edge
    namespace: acubed
spec:
    type: LoadBalancer
    ports:
    - port: 80
    selector:
        app: edge
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
    name: edge 
    namespace: acubed
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edge 
    spec:
      containers:
        - name: edge 
          image: edge
          imagePullPolicy: Always
          ports:
          - containerPort: 80
